#!/usr/bin/env ruby

################################################################################
# Simple threaded MQTT client demo in Ruby
#
# REQUIRED:
#   gem install mqtt
#
# for more info see: 
#   https://github.com/njh/ruby-mqtt
#
# Author: Zvi Avraham <zvi-AT-zadata-DOT-com>
# Copyright (C) 2012-2014 ZADATA Ltd. All Rights Reserved.
################################################################################

require 'mqtt'
require 'uri'

# To find your MQTT Username and Password
# login into your ZADATA account and click  navbar -> "Settings" -> "Credentials"

uri = URI.parse ENV['MQTT_URL'] || 'mqtt://guest:guest@mqtt.zadata.com:1883'

KEEPALIVE_IN_SECS   = 25

MQTT_SETTINGS = {
  remote_host: uri.host,
  remote_port: uri.port,
  username:    uri.user,
  password:    uri.password
  keep_alive:  KEEPALIVE_IN_SECS
}

# Subscribe in a new thread (ClientID autogenerated)
Thread.new do
  MQTT::Client.connect(MQTT_SETTINGS) do |c|
    # The block will be called when you messages arrive to the topic
    c.get('test') do |topic, message|
      puts "#{topic}: #{message}"
    end
  end
end

# Publish example (ClientID autogenerated)
MQTT::Client.connect(MQTT_SETTINGS) do |c|
  loop do
    c.publish('some/long/topic', 'Hello World')
    sleep 1
  end
end
